Fix build issues
GPUOpen-ProfessionalCompute-Libraries/MIVisionX pull request #683
Opened 2021-11-10 17:16 UTC by Indumathi31

1. Fix build issues
2. Fix core dump issue in the sequence reader.

2021-11-10 20:17 UTC, rrawther requested changes

2021-11-10 20:17 UTC, rrawther commented on rocAL/rocAL/source/master_graph.cpp
> +    if(!_is_sequence_reader_output) // _sequence_batch_ratio and _user_to_internal_batch_ratio is different. Will be removed in TensorSupport.
why is this only done when !_is_sequence_reader_output?

2021-11-10 20:17 UTC, rrawther commented on rocAL/rocAL/source/master_graph.cpp
> +#ifdef RALI_VIDEO
put the #ifdef around the entire block

2021-11-17 18:49 UTC, rrawther commented on rocAL/rocAL/source/master_graph.cpp
> +#ifdef RALI_VIDEO
What I meant was the following
#ifdef RALI_VIDEO
    if(_is_video_loader)
    {
        t = _video_loader_module->timing();
        t.video_process_time += _process_time.get_timing();
    }
    else
#endif

2021-11-17 19:16 UTC, rrawther commented on rocAL/rocAL/source/master_graph.cpp
> +#ifdef RALI_VIDEO
Please see the previous comment

2021-11-17 19:16 UTC, rrawther commented
@paveltc : Please run unit-tests on this PR

2021-11-17 19:46 UTC, paveltc commented
@rrawther: I will have the unit tests run and give an update by EOD Thursday 11/18/21 PST.

2021-11-18 04:21 UTC, Indumathi31 commented
@rrawther Have added the change suggested.

2021-11-18 15:08 UTC, paveltc commented
@rrawther This PR passes the rali_unittests and the rali_video_unittests for both the OpenCL and HIP backends.

2021-11-18 20:51 UTC, rrawther approved these changes

2021-11-19 20:03 UTC, merged