Windows - Updates & Fixes
GPUOpen-ProfessionalCompute-Libraries/MIVisionX pull request #844
Opened 2022-05-25 00:03 UTC by kiritigowda

CMakeList - updates
Warning Fix

2022-05-25 16:18 UTC, asalmanp requested changes

2022-05-25 16:18 UTC, asalmanp commented on amd_openvx/openvx/CMakeLists.txt
> +            target_sources(openvx $<TARGET_OBJECTS:openvx_hip>)
@kiritigowda this line causes a CMake error (see [here](http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2FShort-GPUOpen%2FMIVisionX/detail/PR-844/2/pipeline/#step-255-log-1832)), please double-check.

CMake Error at amd_openvx/openvx/CMakeLists.txt:98 (target_sources):
target_sources called with invalid arguments

2022-05-26 06:54 UTC, kiritigowda commented
@asalmanp build on Windows 10/11 & Linux
```
make
[  9%] Built target openvx
[ 10%] Built target vxu
[ 12%] Built target openvx_hip
[ 13%] Built target vx_amd_media
[ 13%] Built target nn_hip
[ 23%] Built target vx_nn
[ 24%] Built target caffe2openvx
[ 45%] Built target vx_rpp
[ 62%] Built target vx_opencv
[ 63%] Built target vx_amd_migraphx
[ 68%] Built target runvx
[ 68%] Built target mv_compile
[100%] Built target rali
[100%] Built target rocAL_hip
```

2022-05-26 17:49 UTC, asalmanp approved these changes

2022-05-26 18:06 UTC, merged