Inference Server App - HIP support
GPUOpen-ProfessionalCompute-Libraries/MIVisionX pull request #857
Opened 2022-06-07 22:36 UTC by hansely

Added HIP support for inference server app
Modified the cmake to build and install inference_server_app under /opt/rocm/bin

2022-06-10 18:39 UTC, rrawther commented on apps/cloud_inference/server_app/CMakeLists.txt
> +    	inference_hip.cpp
please adjust the spacing here

2022-06-10 18:40 UTC, rrawther commented on apps/cloud_inference/server_app/CMakeLists.txt
> -find_package(OpenCL QUIET)
Need to do OpenCV version related changes for supporting both versions(3&4) of OpenCV

2022-06-10 18:42 UTC, rrawther commented on apps/cloud_inference/server_app/inference.cpp
> +#include <opencv2/highgui.hpp>
I think this needs to be changed for OpenCV 4 and above.

2022-06-10 18:47 UTC, rrawther commented on apps/cloud_inference/server_app/CMakeLists.txt
> +	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -msse4.1 -mf16c")
please add -fopenmp flag as well.

2022-06-10 18:49 UTC, rrawther requested changes
Please update based on comments

2022-06-10 21:08 UTC, kiritigowda commented
@hansely use this for OpenCV support in your CMakeList - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/49eac66a6a828bcf8d2c0021da7fc6769c66a345/samples/inference/mv_objdetect/CMakeLists.txt#L65

2022-06-13 21:38 UTC, hansely commented
@kiritigowda Ready to be merged

2022-06-14 17:35 UTC, kiritigowda commented on apps/cloud_inference/server_app/CMakeLists.txt
>  	target_compile_definitions(inference_server_app PUBLIC ENABLE_OPENCV=0)
@hansely take a look at this comment

2022-06-14 17:42 UTC, hansely commented on apps/cloud_inference/server_app/CMakeLists.txt
>  	target_compile_definitions(inference_server_app PUBLIC ENABLE_OPENCV=0)
@kiritigowda removed the definition part

2022-06-14 18:17 UTC, kiritigowda approved these changes

2022-06-14 18:19 UTC, merged