vx_amd_migraphx tests
GPUOpen-ProfessionalCompute-Libraries/MIVisionX pull request #923
Opened 2022-08-18 22:10 UTC by LakshmiKumar23

Updated scripts to take multiple batch sizes. However with TOT MIGraphX repo only batch size = 1 works. TO test on bigger batch sizes , build and install [this branch](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/tree/dyn_reshape_parsing)
Results on confluence page

2022-08-19 17:13 UTC, asalmanp requested changes
@LakshmiKumar23 There are many minor formatting issues with this PR. Please go through all the files and make sure that you follow consistent formatting across all the files. Thanks.

2022-08-19 17:13 UTC, asalmanp commented on tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
> +    outputFile << "iteration,Randomly chosen digit,Result from inference,result\n";
add space after each comma.

2022-08-19 17:13 UTC, asalmanp commented on tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
> +    for(int i = 0; i < batch_size; i++, output_buf+= num_results) {
add a space before +=

2022-08-19 17:13 UTC, asalmanp commented on tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
> +        outputFile << i+1 << "," << rand_digit[i] << "," << answer << "," << (answer == rand_digit[i] ? "Correct":"Incorrect") << "\n";
add a space before and after +

2022-08-19 17:13 UTC, asalmanp commented on tests/amd_migraphx_test/resnet50/migraphx_node_test.cpp
> +    int count = input_dims[0]*input_dims[1]*input_dims[2]*input_dims[3];
add space before and after each *

2022-08-19 17:13 UTC, asalmanp commented on tests/amd_migraphx_test/resnet50/migraphx_node_test.cpp
> +            if ((std::string(pDirent->d_name)).size() > 2)
add curly bracket after the if and else

2022-08-19 17:13 UTC, asalmanp commented on tests/amd_migraphx_test/resnet50/migraphx_node_test.cpp
> +    outputFile << "image,classification,probability,label\n";
add space after each comma

2022-08-19 17:13 UTC, asalmanp commented on tests/amd_migraphx_test/resnet50/migraphx_node_test.cpp
> +        outputFile << i+1 << "," << final_argmax_result << "," << output_buf[final_argmax_result] << "," << output_label.c_str() << "\n";
add space before and after +

2022-08-19 17:13 UTC, asalmanp commented on tests/amd_migraphx_test/runMIGraphXTests/runMIGraphXTests.cpp
> +                float googlenetTime = (float)(t1-t0)*1000.0f/(float)freq/(float)N;
add a space before and after -, and /

2022-08-19 17:17 UTC, LakshmiKumar23 commented on tests/amd_migraphx_test/mnist/CMakeLists.txt
> +include_directories(${OpenCV_INCLUDE_DIRS})
@asalmanp Oh let me undo this. It's only need for the resnet50 test. Even the entire test suite doesn't need it

2022-08-19 17:24 UTC, LakshmiKumar23 commented on tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
> +    vx_size batch_size = stoul(argv[3]);
With TOT MIGraphX only batch size 1, with the link I posted, I have tried till 128

2022-08-19 19:25 UTC, asalmanp requested changes

2022-08-19 19:25 UTC, asalmanp commented on tests/amd_migraphx_test/runMIGraphXTests/runMIGraphXTests.cpp
> +                float resnet50Time = (float)(t1-t0) * 1000.0f / (float)freq / (float)N;
add a space before and after -. there are multiple occurrences of t1-t0 in this file. please fix the formatting for all of them. Thanks.

2022-08-19 20:49 UTC, asalmanp approved these changes
@paveltc please run the MIGraphX tests including the new tests introduced in this PR for the MIGRaphX node. Please check with @LakshmiKumar23 for how to run the tests. Thanks.

2022-08-25 23:19 UTC, kiritigowda commented
@LakshmiKumar23 is this ready to be merged?

2022-08-25 23:20 UTC, LakshmiKumar23 commented
> @LakshmiKumar23 is this ready to be merged?

@kiritigowda No, we need Pavel to run tests and approve it

2022-08-26 20:24 UTC, kiritigowda commented
@paveltc let me know when this good to merge.

2022-08-29 20:42 UTC, paveltc commented
@asalmanp @LakshmiKumar23 @kiritigowda I ran the tests for this PR. It's good to merge.

2022-09-01 17:29 UTC, merged