Zen DNN - Docker & Tests
GPUOpen-ProfessionalCompute-Libraries/MIVisionX pull request #924
Opened 2022-08-20 15:40 UTC by kiritigowda

* Docker
  + CPU Only
  + GPU HIP

* Tests
  + Convolution Test
  + Inference - MNIST 
  + Inference - AlexNet

2022-08-22 21:17 UTC, rrawther commented on tests/zen_dnn_tests/conv/include/test_utils.hpp
> +* Copyright 2019 Intel Corporation
Why this is saying copy right to Intel

2022-08-22 21:18 UTC, rrawther commented on tests/zen_dnn_tests/conv/include/test_utils.hpp
> +* Modifications Copyright (c) 2021 Advanced Micro Devices, Inc. All rights reserved.
FIx correct date

2022-08-22 21:19 UTC, rrawther commented on tests/zen_dnn_tests/mnist/include/test_utils.hpp
> +* Copyright 2019 Intel Corporation
Copyright to Intel??

2022-08-22 21:22 UTC, rrawther requested changes
Do we need to push the binary data for mnist as well. I thought we have it somewhere else. Can we refer from there instead

2022-08-22 21:53 UTC, LakshmiKumar23 reviewed
@kiritigowda can we put all the images in MIVisionX/data? do we want the test images separately here?

2022-08-23 21:25 UTC, LakshmiKumar23 commented
@kiritigowda @rrawther Seems like the test_utils.h file is replicated in all examples, can we have it as a common header file?

2022-08-25 17:36 UTC, merged

2022-08-25 17:42 UTC, LakshmiKumar23 commented
@kiritigowda you deleted the .hpp file altogether

2022-08-25 17:51 UTC, kiritigowda commented
@LakshmiKumar23 yes will use from zen dnn git source