added what Aryan recommended to decoder performance measure code
GPUOpen-ProfessionalCompute-Libraries/MIVisionX pull request #964
Opened 2022-09-29 17:56 UTC by paveltc

2022-09-29 19:57 UTC, asalmanp requested changes

2022-09-29 20:12 UTC, paveltc commented
@asalmanp Added all of the changes.

2022-09-29 20:20 UTC, asalmanp approved these changes
@paveltc 
add

2022-09-29 20:20 UTC, asalmanp commented on amd_openvx_extensions/amd_media/decoder.cpp
> +                    std::cout << "AMD_MEDIA_DECODER Time (ms): " << totalDecodeTime.count() * 1000 / frameno << std::endl;
add the below line after line 737 to report the total transfer time
std::cout << "average transfer time per frame (ms): " << totalTransferTime.count() * 1000 / frameno << std::endl;

2022-10-01 13:43 UTC, asalmanp approved these changes

2022-10-02 05:26 UTC, merged