rocAL Clean up -  CMake and header files
GPUOpen-ProfessionalCompute-Libraries/MIVisionX pull request #991
Opened 2022-10-26 14:41 UTC by shobana-mcw

1. Fix issue with Image aug app CMake
2. CMake clean up in rocAL and rocAL_Pybind
3. Header include clean ups.

2022-10-27 16:04 UTC, LakshmiKumar23 commented
@shobana-mcw This needs a sync up with develop branch

2022-10-27 16:28 UTC, rrawther reviewed
It looks like it is not synced and only files changed shows up

2022-10-28 14:47 UTC, shobana-mcw commented
Updated with TOT.

2022-10-28 21:45 UTC, LakshmiKumar23 requested changes

2022-10-28 21:45 UTC, LakshmiKumar23 commented on apps/image_augmentation/CMakeLists.txt
> +include_directories(${ROCM_PATH}/include/mivisionx/rocal)
@shobana-mcw This cannot be hardcoded. rocm team needs it for spack and other packages

2022-10-31 16:35 UTC, LakshmiKumar23 commented on apps/image_augmentation/CMakeLists.txt
> +include_directories(${ROCM_PATH}/include/mivisionx/rocal)
@shobana-mcw Yes Shobana, you can do it in this PR if it's just those one line changes. Please test the changes

2022-11-01 18:44 UTC, LakshmiKumar23 approved these changes
@kiritigowda ran the test cases. Ok to merge

2022-11-15 21:07 UTC, rrawther approved these changes
@LakshmiKumar23 or @paveltc  to test it.

2022-11-15 21:23 UTC, kiritigowda commented
@LakshmiKumar23 conflict needs to be resolved.

2022-11-15 22:01 UTC, LakshmiKumar23 commented
> @LakshmiKumar23 conflict needs to be resolved.

@kiritigowda I thought it was resolved. @shobana-mcw Can you resolve the merge conflicts?

2022-11-18 01:56 UTC, kiritigowda approved these changes

2022-11-18 01:56 UTC, merged